### ISSUE TITLE
Blog post's text,links and images overlap sidebar

### ISSUE THREAD

**Issue by designviacode** [wakatime/wakatime-blog#1]
![wakatime blogpost bug](https://cloud.githubusercontent.com/assets/7282467/7712752/cb6c5890-fe90-11e4-8fdc-d252e8865a0c.png)
![wakatime blog bug pic2](https://cloud.githubusercontent.com/assets/7282467/7712789/1804e410-fe91-11e4-8d7f-608ee44c8740.png)

All sorts of Text like anchor links,comment Links,normal text and images.. are currently overlapping the left sidebar, also leading to a horizontal scrollbar to appear.

**Comment by alanhamlett** [comment]
Thanks, fixed it now.
