### ISSUE TITLE
Feature: activity can embed

### ISSUE THREAD

**Issue by busyhe** [wakatime/wakatime-blog#13]
it's  beautiful，i want to share. example https://wakatime.com/share/embed. how can i do 
<img width="786" alt="image" src="https://user-images.githubusercontent.com/17348825/183332081-38bc9e12-0de9-4cd2-a99a-147071baef42.png">

**Comment by alanhamlett** [comment]
Continuously updating daily or only share the chart for a specific range never updating?

**Comment by busyhe** [comment]
Continuously updating daily. such as https://ghchart.rshah.org/busyhe. it's repo : https://ghchart.rshah.org/
<img width="770" alt="Xnip2022-08-09_13-39-26" src="https://user-images.githubusercontent.com/17348825/183572909-8bc13929-5282-4620-bad5-f7054269a2ed.png">

**Comment by alanhamlett** [comment]
Added this chart to the embeddables at https://wakatime.com/share/embed

**Comment by busyhe** [comment]
@alanhamlett I love you

**Comment by busyhe** [comment]
@alanhamlett The data are inconsistent
<img width="1706" alt="Xnip2022-08-14_00-07-32" src="https://user-images.githubusercontent.com/17348825/184502107-0e5c87d0-f4a9-4d16-9fbe-db4dd9c66635.png">
<img width="1438" alt="Xnip2022-08-14_00-10-40" src="https://user-images.githubusercontent.com/17348825/184502124-990e44ba-bec1-48ed-91c3-3e01613c55de.png">

**Comment by alanhamlett** [comment]
Try refreshing the page? They both use the same data, but the shareable one has an extra level of caching.

**Comment by busyhe** [comment]
Can't be reproduced. Is it because 00:00:00 time i open two page.😂

**Comment by busyhe** [comment]
@alanhamlett Reappeared！
it's share svg url: https://wakatime.com/share/@busyhe/97ad0c3b-5345-4d6b-81d2-48d2032aca79.svg

<img width="1680" alt="Xnip2022-08-15_10-43-04" src="https://user-images.githubusercontent.com/17348825/184568610-84677b72-8537-4361-9e3c-bb365a60c76f.png">

**Comment by alanhamlett** [comment]
It looks correct to me:

<img width="724" alt="Screen Shot 2022-08-15 at 9 22 56 AM" src="https://user-images.githubusercontent.com/522344/184593165-fabea51d-864d-4400-93e3-cdfb40fc971d.png">

It's probably a delay in updating the cached shareable image.

**Comment by busyhe** [comment]
It should be. such as this https://ghchart.rshah.org/477DA5/busyhe. embed in notion, it updating daily. but wakatime svg embed show old data. it's cache problem？

**Comment by alanhamlett** [comment]
Yes, it's a cache problem. It loads from cache and refreshes in the background, so the second time you load it will be correct but first time it's old.

**Comment by busyhe** [comment]
right! Top is old svg embed. Bottom is new embed.  data not refresh every day.
![Xnip2022-08-17_10-19-21](https://user-images.githubusercontent.com/17348825/185020354-23c31d1f-7eac-48d6-a19e-8b2ee59c003f.png)
