### ISSUE TITLE
embed coding activity table & insights last year data is error?

### ISSUE THREAD

**Issue by busyhe** [wakatime/wakatime-blog#15]
https://wakatime.com/share/@busyhe/97ad0c3b-5345-4d6b-81d2-48d2032aca79.svg
---
<img width="1457" alt="Xnip2023-02-16_20-48-08" src="https://user-images.githubusercontent.com/17348825/219369420-194c4f0f-c68e-44aa-b938-ce454a329b1b.png">
<img width="1465" alt="Xnip2023-02-16_20-49-21" src="https://user-images.githubusercontent.com/17348825/219369439-4ac89c0a-82f8-4747-ac7c-62759012a5a8.png">

**Comment by alanhamlett** [comment]
Refresh the embeddable chart page, it's just showing cached old data.
