### ISSUE TITLE
Relationships when declaring models with `db.ForeignKey()`

### ISSUE THREAD

**Issue by ccrvlh** [wakatime/wakatime-blog#5]
Hey mate.
First, thanks a lot for the effort to put this together and publish it. It's amazing how hard it is to find good content on a topic that 'should' be simple for begginers such as myself.

That being said, I was wondering with the "relationship" feature would work when instead of declaring relationships with `db.relationship` the models are declared with `datacol = db.Column(INTEGER(11), db.ForeingKey('parent.id'))`.

Thanks a lot.

**Comment by alanhamlett** [comment]
In [post 32](https://github.com/wakatime/wakatime-blog/blob/15996ed1e54bad80e0ac97550fd0446edb8e9eaa/posts/32-flask-part-1-sqlalchemy-models-as-json.md#relationships), the `db` variable is a [Flask-Sqlalchemy](https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/#simple-relationships) object so you can do anything that Flask-SQLAlchemy or SQLAlchemy supports.
