### ISSUE TITLE
Numbers don't add up

### ISSUE THREAD

**Issue by finfin** [wakatime/wakatime-blog#7]
The first sentence "In 2020, more than 250k developers spent a combined 36 million hours programming"
would calculated as roughly 150hr per developer/year
This does not match the second sentence "The average person spent 51 minutes per day programming."
Which is more related to https://wakatime.com/a-look-back-at-2020 , stated as 313hr per developer / year

Also, the first graph shows Dart as +0.9% compared with last year, but there's not stat on Dart in last year's blog https://wakatime.com/blog/40-wakatime-2019-programming-stats

**Comment by alanhamlett** [comment]
`51 minutes per day` is the average of all users' daily average, which skips days with zero seconds logged. For ex: if you only coded 2 hours in 2020 and all those 2 hours were logged on the same day, your daily average would be 2 hours.

In 2019 `Dart` barely missed the cut, it would have been the next language at the bottom of the chart. In 2019, Dart had a sum of `250,541 hrs` (https://wakatime.com/api/v1/stats/2019).

Everything looks good to me.
